name: Deploy to webserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v5.0.0
      
      - name: setup Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '20.9.0'
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: install client dependencies
        working-directory: ./client
        run: npm ci

      - name: install server dependencies
        working-directory: ./server
        run: npm ci

      - name: build Next.js
        working-directory: ./client
        run: npm run build

      - name: ssh setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "|1|o+5Tp931+T9Qqxup5onr/grw3Ps=|SkZNIKMk9h+vdWUfUOfo7fRYMCI= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOE/MN8knHNCJCGIxmT78aXQX2MaTs+sG3UiQj5oUDaV" >> ~/.ssh/known_hosts
      
      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }}" \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.env' \
            --exclude='.next/cache' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SSH_HOST }}:/home/webmaster/full-stack-blog/ \
            --dry-run
